#!/usr/bin/env python3
r"""
gh-pr-create.py — 创建 GitHub Pull Request（独立脚本，模块化）
标签：py-tools
版本：v1.1.0（新增 --auto AI title 生成）

职责：从当前分支创建 PR，支持指定标题、正文、目标分支。
      新增 --auto 模式：自动读取 feature 分支 commits + 变更统计，
      调用 AI 生成概括性 PR title（中文，conventional commits 格式）。
      复用 gh_preflight 插件做前置验证，可独立执行，也可被上层 workflow 编排调用。

参数：
| 参数 | 类型 | 必填 | 默认值 | 说明 |
|------|------|------|--------|------|
| --devroot | str | 否 | D:\pjt\cursor\cs_py | devroot 绝对路径 |
| --title | str | 条件 | — | PR 标题（与 --auto 互斥） |
| --auto | flag | 否 | False | 自动生成 PR title（与 --title 互斥） |
| --body | str | 否 | "Auto-generated by gh-pr-create" | PR 正文 |
| --base | str | 否 | master | 目标分支 |
| --draft | flag | 否 | False | 创建为 Draft PR |

调用示例：
  # 手动指定 title
  & "D:\pjt\cursor\cs_py\venv\py\python.exe" "...\gh-pr-create.py" --title "feat: xxx"

  # AI 自动生成 title（推荐，全链条用）
  & "D:\pjt\cursor\cs_py\venv\py\python.exe" "...\gh-pr-create.py" --auto --base master

返回：
  成功时 stdout 最后一行输出 PR URL，如 "https://github.com/owner/repo/pull/123"
  失败时 exit code 非 0
"""
import argparse
import subprocess
import sys
import time
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

_SCRIPTS_DIR = Path(__file__).parent.parent.resolve()
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))


def _get_commits(devroot: Path, current_branch: str, base: str) -> tuple[list[str], str]:
    """
    获取 feature 分支相对 base 的所有 commits 和变更统计。

    返回:
        (commits_lines, stat_text)
    """
    git_exe = devroot / "venv" / "git" / "cmd" / "git.exe"

    # 1. commits oneline
    r = subprocess.run(
        [str(git_exe), "-C", str(devroot), "log", f"{base}..{current_branch}", "--oneline", "--reverse"],
        capture_output=True, text=True, encoding="utf-8", errors="replace"
    )
    commits = [ln.strip() for ln in r.stdout.strip().splitlines() if ln.strip()]

    # 2. diff stat
    r2 = subprocess.run(
        [str(git_exe), "-C", str(devroot), "diff", f"{base}..{current_branch}", "--stat"],
        capture_output=True, text=True, encoding="utf-8", errors="replace"
    )
    stat = r2.stdout.strip()

    return commits, stat


def _generate_pr_title(devroot: Path, current_branch: str, base: str) -> str:
    """
    调用 AI 根据 feature 分支 commits 生成概括性 PR title。
    失败时 fallback 到默认 title。
    """
    commits, stat = _get_commits(devroot, current_branch, base)
    if not commits:
        print("[WARN] 无 commits 可分析，使用 fallback title")
        return f"feat: changes from {current_branch}"

    commits_text = "\n".join(f"- {c}" for c in commits)
    prompt = f"""你是一位资深产品经理。请根据以下 feature 分支的 commits，生成一个简洁的 GitHub PR title。

Commits:
{commits_text}

变更统计：
{stat}

要求：
1. 用 conventional commits 格式（如 feat:/fix:/refactor:）
2. 一行，不超过 72 个字符
3. 概括整个 feature 的主题，不是罗列每个 commit
4. 使用中文

请直接输出 title，不要添加任何前言或解释。
"""

    print("[AI] 正在生成 PR title...")
    start = time.time()
    try:
        from py_lib import load_plugins
        registry = load_plugins(devroot=str(devroot), profile="agent")
        provider_cfg = registry.provider_config.get_provider(source="config_json")
        agent = registry.agent_core.AgentCore(
            enable_tools=False,
            provider_cfg=provider_cfg,
        )
        title = agent.run(
            prompt=prompt,
            system="你是资深产品经理，擅长用中文一句话概括功能变更的主题。",
            max_turns=1,
        )
        elapsed = time.time() - start
        # 清理输出（去掉多余引号/换行）
        title = title.strip().strip('"').strip("'").splitlines()[0].strip()
        if len(title) > 72:
            title = title[:72]
        print(f"[AI] PR title 生成完成 (耗时 {elapsed:.2f}s): {title}")
        return title
    except Exception as e:
        elapsed = time.time() - start
        print(f"[AI] PR title 生成失败 (耗时 {elapsed:.2f}s): {e}")
        fallback = f"feat: changes from {current_branch}"
        print(f"[AI] fallback: {fallback}")
        return fallback


def main():
    parser = argparse.ArgumentParser(description="创建 GitHub Pull Request")
    parser.add_argument("--devroot", default=r"D:\pjt\cursor\cs_py", help="Devroot 路径")
    parser.add_argument("--title", default=None, help="PR 标题（与 --auto 互斥）")
    parser.add_argument("--auto", action="store_true", help="自动生成 PR title（与 --title 互斥）")
    parser.add_argument("--body", default="Auto-generated by gh-pr-create", help="PR 正文")
    parser.add_argument("--base", default="master", help="目标分支（默认 master）")
    parser.add_argument("--draft", action="store_true", help="创建为 Draft PR")
    args = parser.parse_args()

    if args.title and args.auto:
        print("[FAIL] --title 与 --auto 互斥，请只传其中一个")
        sys.exit(1)
    if not args.title and not args.auto:
        print("[FAIL] 必须指定 --title 或 --auto")
        sys.exit(1)

    devroot = Path(args.devroot)

    # Step 0: gh preflight
    from py_lib import load_plugins
    registry = load_plugins(devroot=str(devroot), tags=["gh"])
    ctx = registry.gh_preflight.check()

    # Step 1: 获取当前分支名
    git_exe = devroot / "venv" / "git" / "cmd" / "git.exe"
    r = subprocess.run(
        [str(git_exe), "-C", str(devroot), "branch", "--show-current"],
        capture_output=True, text=True, encoding="utf-8"
    )
    if r.returncode != 0:
        print(f"[FAIL] 无法获取当前分支: {r.stderr.strip()}")
        sys.exit(1)
    current_branch = r.stdout.strip()
    if current_branch == args.base:
        print(f"[FAIL] 当前分支 ({current_branch}) 与目标分支 ({args.base}) 相同，无法创建 PR")
        sys.exit(1)
    print(f"[OK] 当前分支: {current_branch} -> 目标分支: {args.base}")

    # Step 2: 确定 PR title
    if args.auto:
        pr_title = _generate_pr_title(devroot, current_branch, args.base)
    else:
        pr_title = args.title
    print(f"[OK] PR title: {pr_title}")

    # Step 3: 检查远程是否存在同名分支（push 了吗）
    r = subprocess.run(
        [str(git_exe), "-C", str(devroot), "ls-remote", "--heads", "origin", current_branch],
        capture_output=True, text=True, encoding="utf-8"
    )
    if not r.stdout.strip():
        print(f"[WARN] 远程不存在分支 {current_branch}，尝试自动 push...")
        push_r = subprocess.run(
            [str(git_exe), "-C", str(devroot), "push", "-u", "origin", current_branch],
            capture_output=True, text=True, encoding="utf-8"
        )
        if push_r.returncode != 0:
            print(f"[FAIL] push 失败: {push_r.stderr.strip()}")
            sys.exit(1)
        print(f"[OK] 已 push 分支 {current_branch} 到 origin")

    # Step 4: gh pr create
    print(f"\n{'='*50}")
    print("[Step] gh pr create")
    print(f"{'='*50}")

    cmd = [
        "pr", "create",
        "--title", pr_title,
        "--body", args.body,
        "--base", args.base,
    ]
    if args.draft:
        cmd.append("--draft")

    r = ctx.run_gh(cmd)
    if r.returncode != 0:
        print(f"[FAIL] gh pr create 失败:\n{r.stderr.strip()}")
        sys.exit(1)

    # 提取 PR URL（gh pr create 成功时 stdout 最后一行通常是 URL）
    output_lines = [ln for ln in r.stdout.strip().splitlines() if ln.strip()]
    pr_url = output_lines[-1] if output_lines else ""
    print(f"[OK] PR 创建成功: {pr_url}")
    print(f"[Output] PR_URL={pr_url}")


if __name__ == "__main__":
    main()
